version: 2

sources:
  - name: denormalize
    description: 'Transformation to denormalize movie directors and role actors.'
    database: "{{ var('DBT_DB_SCHEMA') }}"
    schema: "{{ var('DBT_DB_SCHEMA') }}"
    tables:
      - name: movies
        identifier: movies

      - name: movies_directors
        identifier: movies_directors

      - name: actors
        identifier: actors

      - name: directors_genres
        identifier: directors_genres
      
      - name: directors
        identifier: directors
      
      - name: roles
        identifier: roles
        
      - name: movies_genres
        identifier: movies_genres

      - name: movie_directors
        description: 'Movie directors'
        # 'director_id': 'int',
        # 'movie_id': 'int',
        # 'first_name': 'varchar(100)',
        # 'last_name': 'varchar(100)',
        # 'genre': 'varchar(100)',
        # 'prob': 'float'
        columns:
          - name: director_id
            description: 'Director ID'
            tests:
              - unique
              - not null
          - name: movie_id
            description: 'Movie ID'
            tests:
              - relationships:
                  to: source('denormalize', 'movies')
                  field: id
          - name: first_name
            description: 'Director first name'
          - name: last_name
            description: 'Director last name'
            tests:
              - not_null
          - name: genre
            description: 'Movie genre'
          - name: prob
        
      - name: role_actors
        description: 'Role actors'
        # 'movie_id': 'varchar(100)',
        # 'role': 'varchar(100)',
        # 'actor_first_name': 'varchar(100)',
        # 'actor_last_name': 'varchar(100)',
        # 'actor_gender': 'char(1)'
        columns:
          - name: movie_id
            description: 'Movie ID'
            tests:
              - relationships:
                  to: source('denormalize', 'movies')
                  field: id
          - name: role
            description: 'Role'
          - name: actor_first_name
            description: 'Actor first name'
          - name: actor_last_name
            description: 'Actor last name'
          - name: actor_gender
            description: 'Actor gender'