config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true

normalize:
  target: prod
  outputs:
    prod:
      type: mysql
      database: "{{ var('DBT_DB_SCHEMA') }}"
      password: "{{ var('DBT_DB_PASSWORD') }}"
      port: 3306
      schema: "{{ var('DBT_DB_SCHEMA') }}"
      server: "{{ var('DBT_SERVER') }}"
      username: "{{ var('DBT_DB_USER') }}"